services:
  api:
    image: roeldev/demo-chatroom-api:local
    build:
      context: .
      args:
        APP: api-server
    user: nonroot
    env_file:
      - ./cmd/api-server/.env
    environment:
      LOG_LEVEL: info
      CORS_ALLOW_ORIGINS: http://localhost:8081,http://localhost:5173
    networks:
      - public
      - internal
    ports:
      - "8080:8080"

  web:
    image: roeldev/demo-chatroom-web:local
    build:
      context: .
      args:
        APP: web-server
    user: nonroot
    env_file:
      - ./cmd/web-server/.env
    depends_on:
      - api
    networks:
      - public
      - internal
    ports:
      - "8081:8080"

  chatter-bot:
    image: roeldev/demo-chatroom-chatter-bot:local
    build:
      context: .
      args:
        APP: chatter-bot
    user: nonroot
    env_file:
      - ./cmd/chatter-bot/.env
    environment:
#      LOG_LEVEL: debug
      API_SERVER_HOST: api
    depends_on:
      - api
    networks:
      - internal
    deploy:
      replicas: 8
      mode: replicated

  welcome-bot:
    image: roeldev/demo-chatroom-welcome-bot:local
    build:
      context: .
      args:
        APP: welcome-bot
    user: nonroot
    env_file:
      - ./cmd/welcome-bot/.env
    environment:
#      LOG_LEVEL: debug
      API_SERVER_HOST: api
    depends_on:
      - api
    networks:
      - internal

networks:
  public:
    driver: bridge
  internal:
