// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: api/v1/apiv1.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"
	_ "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserStatus int32

const (
	UserStatus_Default UserStatus = 0
	UserStatus_Busy    UserStatus = 1
	UserStatus_Away    UserStatus = 2
)

// Enum value maps for UserStatus.
var (
	UserStatus_name = map[int32]string{
		0: "Default",
		1: "Busy",
		2: "Away",
	}
	UserStatus_value = map[string]int32{
		"Default": 0,
		"Busy":    1,
		"Away":    2,
	}
)

func (x UserStatus) Enum() *UserStatus {
	p := new(UserStatus)
	*p = x
	return p
}

func (x UserStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_apiv1_proto_enumTypes[0].Descriptor()
}

func (UserStatus) Type() protoreflect.EnumType {
	return &file_api_v1_apiv1_proto_enumTypes[0]
}

func (x UserStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserStatus.Descriptor instead.
func (UserStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_apiv1_proto_rawDescGZIP(), []int{0}
}

type UserFlag int32

const (
	UserFlag_None  UserFlag = 0
	UserFlag_IsBot UserFlag = 1
)

// Enum value maps for UserFlag.
var (
	UserFlag_name = map[int32]string{
		0: "None",
		1: "IsBot",
	}
	UserFlag_value = map[string]int32{
		"None":  0,
		"IsBot": 1,
	}
)

func (x UserFlag) Enum() *UserFlag {
	p := new(UserFlag)
	*p = x
	return p
}

func (x UserFlag) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserFlag) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_apiv1_proto_enumTypes[1].Descriptor()
}

func (UserFlag) Type() protoreflect.EnumType {
	return &file_api_v1_apiv1_proto_enumTypes[1]
}

func (x UserFlag) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserFlag.Descriptor instead.
func (UserFlag) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_apiv1_proto_rawDescGZIP(), []int{1}
}

// //////////////////////////////////////////////////////////////////////////////
// General messages
type UUID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UUID) Reset() {
	*x = UUID{}
	mi := &file_api_v1_apiv1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UUID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UUID) ProtoMessage() {}

func (x *UUID) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_apiv1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UUID.ProtoReflect.Descriptor instead.
func (*UUID) Descriptor() ([]byte, []int) {
	return file_api_v1_apiv1_proto_rawDescGZIP(), []int{0}
}

func (x *UUID) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Color struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Color) Reset() {
	*x = Color{}
	mi := &file_api_v1_apiv1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Color) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Color) ProtoMessage() {}

func (x *Color) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_apiv1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Color.ProtoReflect.Descriptor instead.
func (*Color) Descriptor() ([]byte, []int) {
	return file_api_v1_apiv1_proto_rawDescGZIP(), []int{1}
}

func (x *Color) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type UserDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Initials      string                 `protobuf:"bytes,2,opt,name=initials" json:"initials,omitempty"` // max 3 chars
	Color1        *Color                 `protobuf:"bytes,3,opt,name=color1" json:"color1,omitempty"`     // avatar background
	Color2        *Color                 `protobuf:"bytes,4,opt,name=color2" json:"color2,omitempty"`     // avatar text
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDetails) Reset() {
	*x = UserDetails{}
	mi := &file_api_v1_apiv1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDetails) ProtoMessage() {}

func (x *UserDetails) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_apiv1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDetails.ProtoReflect.Descriptor instead.
func (*UserDetails) Descriptor() ([]byte, []int) {
	return file_api_v1_apiv1_proto_rawDescGZIP(), []int{2}
}

func (x *UserDetails) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserDetails) GetInitials() string {
	if x != nil {
		return x.Initials
	}
	return ""
}

func (x *UserDetails) GetColor1() *Color {
	if x != nil {
		return x.Color1
	}
	return nil
}

func (x *UserDetails) GetColor2() *Color {
	if x != nil {
		return x.Color2
	}
	return nil
}

type UserMention struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        *UUID                  `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=user_name,json=userName" json:"user_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserMention) Reset() {
	*x = UserMention{}
	mi := &file_api_v1_apiv1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserMention) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMention) ProtoMessage() {}

func (x *UserMention) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_apiv1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMention.ProtoReflect.Descriptor instead.
func (*UserMention) Descriptor() ([]byte, []int) {
	return file_api_v1_apiv1_proto_rawDescGZIP(), []int{3}
}

func (x *UserMention) GetUserId() *UUID {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *UserMention) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type JoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserDetails           `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	Flags         UserFlag               `protobuf:"varint,2,opt,name=flags,enum=api.v1.UserFlag" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_api_v1_apiv1_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_apiv1_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_apiv1_proto_rawDescGZIP(), []int{4}
}

func (x *JoinRequest) GetUser() *UserDetails {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *JoinRequest) GetFlags() UserFlag {
	if x != nil {
		return x.Flags
	}
	return UserFlag_None
}

type JoinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinResponse) Reset() {
	*x = JoinResponse{}
	mi := &file_api_v1_apiv1_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponse) ProtoMessage() {}

func (x *JoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_apiv1_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponse.ProtoReflect.Descriptor instead.
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_apiv1_proto_rawDescGZIP(), []int{5}
}

func (x *JoinResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type RenewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewResponse) Reset() {
	*x = RenewResponse{}
	mi := &file_api_v1_apiv1_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewResponse) ProtoMessage() {}

func (x *RenewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_apiv1_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewResponse.ProtoReflect.Descriptor instead.
func (*RenewResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_apiv1_proto_rawDescGZIP(), []int{6}
}

func (x *RenewResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ActiveUsersResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Time          *timestamppb.Timestamp      `protobuf:"bytes,1,opt,name=time" json:"time,omitempty"`
	Users         []*ActiveUsersResponse_User `protobuf:"bytes,2,rep,name=users" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActiveUsersResponse) Reset() {
	*x = ActiveUsersResponse{}
	mi := &file_api_v1_apiv1_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveUsersResponse) ProtoMessage() {}

func (x *ActiveUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_apiv1_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveUsersResponse.ProtoReflect.Descriptor instead.
func (*ActiveUsersResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_apiv1_proto_rawDescGZIP(), []int{7}
}

func (x *ActiveUsersResponse) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *ActiveUsersResponse) GetUsers() []*ActiveUsersResponse_User {
	if x != nil {
		return x.Users
	}
	return nil
}

type UpdateDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Details       *UserDetails           `protobuf:"bytes,1,opt,name=details" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDetailsRequest) Reset() {
	*x = UpdateDetailsRequest{}
	mi := &file_api_v1_apiv1_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDetailsRequest) ProtoMessage() {}

func (x *UpdateDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_apiv1_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDetailsRequest.ProtoReflect.Descriptor instead.
func (*UpdateDetailsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_apiv1_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateDetailsRequest) GetDetails() *UserDetails {
	if x != nil {
		return x.Details
	}
	return nil
}

type UpdateStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        UserStatus             `protobuf:"varint,1,opt,name=status,enum=api.v1.UserStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusRequest) Reset() {
	*x = UpdateStatusRequest{}
	mi := &file_api_v1_apiv1_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusRequest) ProtoMessage() {}

func (x *UpdateStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_apiv1_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_apiv1_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateStatusRequest) GetStatus() UserStatus {
	if x != nil {
		return x.Status
	}
	return UserStatus_Default
}

type IndicateTypingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// no receiver = global chatroom
	ReceiverId    *UUID `protobuf:"bytes,1,opt,name=receiver_id,json=receiverId" json:"receiver_id,omitempty"`
	Typing        bool  `protobuf:"varint,2,opt,name=typing" json:"typing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndicateTypingRequest) Reset() {
	*x = IndicateTypingRequest{}
	mi := &file_api_v1_apiv1_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndicateTypingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndicateTypingRequest) ProtoMessage() {}

func (x *IndicateTypingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_apiv1_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndicateTypingRequest.ProtoReflect.Descriptor instead.
func (*IndicateTypingRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_apiv1_proto_rawDescGZIP(), []int{10}
}

func (x *IndicateTypingRequest) GetReceiverId() *UUID {
	if x != nil {
		return x.ReceiverId
	}
	return nil
}

func (x *IndicateTypingRequest) GetTyping() bool {
	if x != nil {
		return x.Typing
	}
	return false
}

type SendChatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Time  *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time" json:"time,omitempty"`
	// no receiver = global chatroom
	ReceiverId    *UUID          `protobuf:"bytes,2,opt,name=receiver_id,json=receiverId" json:"receiver_id,omitempty"`
	ReplyChatId   *UUID          `protobuf:"bytes,3,opt,name=reply_chat_id,json=replyChatId" json:"reply_chat_id,omitempty"`
	Text          string         `protobuf:"bytes,4,opt,name=text" json:"text,omitempty"`
	Mentions      []*UserMention `protobuf:"bytes,5,rep,name=mentions" json:"mentions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendChatRequest) Reset() {
	*x = SendChatRequest{}
	mi := &file_api_v1_apiv1_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendChatRequest) ProtoMessage() {}

func (x *SendChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_apiv1_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendChatRequest.ProtoReflect.Descriptor instead.
func (*SendChatRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_apiv1_proto_rawDescGZIP(), []int{11}
}

func (x *SendChatRequest) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *SendChatRequest) GetReceiverId() *UUID {
	if x != nil {
		return x.ReceiverId
	}
	return nil
}

func (x *SendChatRequest) GetReplyChatId() *UUID {
	if x != nil {
		return x.ReplyChatId
	}
	return nil
}

func (x *SendChatRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SendChatRequest) GetMentions() []*UserMention {
	if x != nil {
		return x.Mentions
	}
	return nil
}

type EditChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time" json:"time,omitempty"`
	ChatId        *UUID                  `protobuf:"bytes,2,opt,name=chat_id,json=chatId" json:"chat_id,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditChatRequest) Reset() {
	*x = EditChatRequest{}
	mi := &file_api_v1_apiv1_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditChatRequest) ProtoMessage() {}

func (x *EditChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_apiv1_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditChatRequest.ProtoReflect.Descriptor instead.
func (*EditChatRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_apiv1_proto_rawDescGZIP(), []int{12}
}

func (x *EditChatRequest) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *EditChatRequest) GetChatId() *UUID {
	if x != nil {
		return x.ChatId
	}
	return nil
}

func (x *EditChatRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type EmojiReplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time" json:"time,omitempty"`
	ReplyChatId   *UUID                  `protobuf:"bytes,3,opt,name=reply_chat_id,json=replyChatId" json:"reply_chat_id,omitempty"`
	Emoji         []byte                 `protobuf:"bytes,4,opt,name=emoji" json:"emoji,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmojiReplyRequest) Reset() {
	*x = EmojiReplyRequest{}
	mi := &file_api_v1_apiv1_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmojiReplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmojiReplyRequest) ProtoMessage() {}

func (x *EmojiReplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_apiv1_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmojiReplyRequest.ProtoReflect.Descriptor instead.
func (*EmojiReplyRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_apiv1_proto_rawDescGZIP(), []int{13}
}

func (x *EmojiReplyRequest) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *EmojiReplyRequest) GetReplyChatId() *UUID {
	if x != nil {
		return x.ReplyChatId
	}
	return nil
}

func (x *EmojiReplyRequest) GetEmoji() []byte {
	if x != nil {
		return x.Emoji
	}
	return nil
}

type EventUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *UUID                  `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Details       *UserDetails           `protobuf:"bytes,2,opt,name=details" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventUser) Reset() {
	*x = EventUser{}
	mi := &file_api_v1_apiv1_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventUser) ProtoMessage() {}

func (x *EventUser) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_apiv1_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventUser.ProtoReflect.Descriptor instead.
func (*EventUser) Descriptor() ([]byte, []int) {
	return file_api_v1_apiv1_proto_rawDescGZIP(), []int{14}
}

func (x *EventUser) GetId() *UUID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *EventUser) GetDetails() *UserDetails {
	if x != nil {
		return x.Details
	}
	return nil
}

type PreviousEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UntilTime     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=until_time,json=untilTime" json:"until_time,omitempty"`
	Limit         uint64                 `protobuf:"varint,2,opt,name=limit" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviousEventsRequest) Reset() {
	*x = PreviousEventsRequest{}
	mi := &file_api_v1_apiv1_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviousEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviousEventsRequest) ProtoMessage() {}

func (x *PreviousEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_apiv1_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviousEventsRequest.ProtoReflect.Descriptor instead.
func (*PreviousEventsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_apiv1_proto_rawDescGZIP(), []int{15}
}

func (x *PreviousEventsRequest) GetUntilTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UntilTime
	}
	return nil
}

func (x *PreviousEventsRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type PreviousEventsResponse struct {
	state         protoimpl.MessageState                  `protogen:"open.v1"`
	History       []*PreviousEventsResponse_PreviousEvent `protobuf:"bytes,1,rep,name=history" json:"history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviousEventsResponse) Reset() {
	*x = PreviousEventsResponse{}
	mi := &file_api_v1_apiv1_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviousEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviousEventsResponse) ProtoMessage() {}

func (x *PreviousEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_apiv1_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviousEventsResponse.ProtoReflect.Descriptor instead.
func (*PreviousEventsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_apiv1_proto_rawDescGZIP(), []int{16}
}

func (x *PreviousEventsResponse) GetHistory() []*PreviousEventsResponse_PreviousEvent {
	if x != nil {
		return x.History
	}
	return nil
}

type EventStreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Stream:
	//
	//	*EventStreamRequest_Start
	//	*EventStreamRequest_Ack
	Stream        isEventStreamRequest_Stream `protobuf_oneof:"stream"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventStreamRequest) Reset() {
	*x = EventStreamRequest{}
	mi := &file_api_v1_apiv1_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventStreamRequest) ProtoMessage() {}

func (x *EventStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_apiv1_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventStreamRequest.ProtoReflect.Descriptor instead.
func (*EventStreamRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_apiv1_proto_rawDescGZIP(), []int{17}
}

func (x *EventStreamRequest) GetStream() isEventStreamRequest_Stream {
	if x != nil {
		return x.Stream
	}
	return nil
}

func (x *EventStreamRequest) GetStart() string {
	if x != nil {
		if x, ok := x.Stream.(*EventStreamRequest_Start); ok {
			return x.Start
		}
	}
	return ""
}

func (x *EventStreamRequest) GetAck() string {
	if x != nil {
		if x, ok := x.Stream.(*EventStreamRequest_Ack); ok {
			return x.Ack
		}
	}
	return ""
}

type isEventStreamRequest_Stream interface {
	isEventStreamRequest_Stream()
}

type EventStreamRequest_Start struct {
	Start string `protobuf:"bytes,1,opt,name=start,oneof"`
}

type EventStreamRequest_Ack struct {
	Ack string `protobuf:"bytes,2,opt,name=ack,oneof"`
}

func (*EventStreamRequest_Start) isEventStreamRequest_Stream() {}

func (*EventStreamRequest_Ack) isEventStreamRequest_Stream() {}

type EventStreamResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Time  *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time" json:"time,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*EventStreamResponse_UserJoin
	//	*EventStreamResponse_UserLeave
	//	*EventStreamResponse_UserUpdate
	//	*EventStreamResponse_UserStatus
	//	*EventStreamResponse_UserTyping
	//	*EventStreamResponse_ChatSent
	//	*EventStreamResponse_ChatEdit
	//	*EventStreamResponse_EmojiReply
	//	*EventStreamResponse_EmojiRemove
	Event         isEventStreamResponse_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventStreamResponse) Reset() {
	*x = EventStreamResponse{}
	mi := &file_api_v1_apiv1_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventStreamResponse) ProtoMessage() {}

func (x *EventStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_apiv1_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventStreamResponse.ProtoReflect.Descriptor instead.
func (*EventStreamResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_apiv1_proto_rawDescGZIP(), []int{18}
}

func (x *EventStreamResponse) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *EventStreamResponse) GetEvent() isEventStreamResponse_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *EventStreamResponse) GetUserJoin() *UserJoinEvent {
	if x != nil {
		if x, ok := x.Event.(*EventStreamResponse_UserJoin); ok {
			return x.UserJoin
		}
	}
	return nil
}

func (x *EventStreamResponse) GetUserLeave() *UserLeaveEvent {
	if x != nil {
		if x, ok := x.Event.(*EventStreamResponse_UserLeave); ok {
			return x.UserLeave
		}
	}
	return nil
}

func (x *EventStreamResponse) GetUserUpdate() *UserUpdateEvent {
	if x != nil {
		if x, ok := x.Event.(*EventStreamResponse_UserUpdate); ok {
			return x.UserUpdate
		}
	}
	return nil
}

func (x *EventStreamResponse) GetUserStatus() *UserStatusEvent {
	if x != nil {
		if x, ok := x.Event.(*EventStreamResponse_UserStatus); ok {
			return x.UserStatus
		}
	}
	return nil
}

func (x *EventStreamResponse) GetUserTyping() *UserTypingEvent {
	if x != nil {
		if x, ok := x.Event.(*EventStreamResponse_UserTyping); ok {
			return x.UserTyping
		}
	}
	return nil
}

func (x *EventStreamResponse) GetChatSent() *ChatSentEvent {
	if x != nil {
		if x, ok := x.Event.(*EventStreamResponse_ChatSent); ok {
			return x.ChatSent
		}
	}
	return nil
}

func (x *EventStreamResponse) GetChatEdit() *ChatEditEvent {
	if x != nil {
		if x, ok := x.Event.(*EventStreamResponse_ChatEdit); ok {
			return x.ChatEdit
		}
	}
	return nil
}

func (x *EventStreamResponse) GetEmojiReply() *EmojiReplyEvent {
	if x != nil {
		if x, ok := x.Event.(*EventStreamResponse_EmojiReply); ok {
			return x.EmojiReply
		}
	}
	return nil
}

func (x *EventStreamResponse) GetEmojiRemove() *EmojiRemoveEvent {
	if x != nil {
		if x, ok := x.Event.(*EventStreamResponse_EmojiRemove); ok {
			return x.EmojiRemove
		}
	}
	return nil
}

type isEventStreamResponse_Event interface {
	isEventStreamResponse_Event()
}

type EventStreamResponse_UserJoin struct {
	UserJoin *UserJoinEvent `protobuf:"bytes,10,opt,name=user_join,json=userJoin,oneof"`
}

type EventStreamResponse_UserLeave struct {
	UserLeave *UserLeaveEvent `protobuf:"bytes,11,opt,name=user_leave,json=userLeave,oneof"`
}

type EventStreamResponse_UserUpdate struct {
	UserUpdate *UserUpdateEvent `protobuf:"bytes,12,opt,name=user_update,json=userUpdate,oneof"`
}

type EventStreamResponse_UserStatus struct {
	UserStatus *UserStatusEvent `protobuf:"bytes,13,opt,name=user_status,json=userStatus,oneof"`
}

type EventStreamResponse_UserTyping struct {
	UserTyping *UserTypingEvent `protobuf:"bytes,14,opt,name=user_typing,json=userTyping,oneof"`
}

type EventStreamResponse_ChatSent struct {
	ChatSent *ChatSentEvent `protobuf:"bytes,20,opt,name=chat_sent,json=chatSent,oneof"`
}

type EventStreamResponse_ChatEdit struct {
	ChatEdit *ChatEditEvent `protobuf:"bytes,21,opt,name=chat_edit,json=chatEdit,oneof"`
}

type EventStreamResponse_EmojiReply struct {
	EmojiReply *EmojiReplyEvent `protobuf:"bytes,22,opt,name=emoji_reply,json=emojiReply,oneof"`
}

type EventStreamResponse_EmojiRemove struct {
	EmojiRemove *EmojiRemoveEvent `protobuf:"bytes,23,opt,name=emoji_remove,json=emojiRemove,oneof"`
}

func (*EventStreamResponse_UserJoin) isEventStreamResponse_Event() {}

func (*EventStreamResponse_UserLeave) isEventStreamResponse_Event() {}

func (*EventStreamResponse_UserUpdate) isEventStreamResponse_Event() {}

func (*EventStreamResponse_UserStatus) isEventStreamResponse_Event() {}

func (*EventStreamResponse_UserTyping) isEventStreamResponse_Event() {}

func (*EventStreamResponse_ChatSent) isEventStreamResponse_Event() {}

func (*EventStreamResponse_ChatEdit) isEventStreamResponse_Event() {}

func (*EventStreamResponse_EmojiReply) isEventStreamResponse_Event() {}

func (*EventStreamResponse_EmojiRemove) isEventStreamResponse_Event() {}

// User joins
type UserJoinEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *EventUser             `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	Flags         UserFlag               `protobuf:"varint,2,opt,name=flags,enum=api.v1.UserFlag" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserJoinEvent) Reset() {
	*x = UserJoinEvent{}
	mi := &file_api_v1_apiv1_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserJoinEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserJoinEvent) ProtoMessage() {}

func (x *UserJoinEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_apiv1_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserJoinEvent.ProtoReflect.Descriptor instead.
func (*UserJoinEvent) Descriptor() ([]byte, []int) {
	return file_api_v1_apiv1_proto_rawDescGZIP(), []int{19}
}

func (x *UserJoinEvent) GetUser() *EventUser {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UserJoinEvent) GetFlags() UserFlag {
	if x != nil {
		return x.Flags
	}
	return UserFlag_None
}

// User leaves
type UserLeaveEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *EventUser             `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLeaveEvent) Reset() {
	*x = UserLeaveEvent{}
	mi := &file_api_v1_apiv1_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLeaveEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLeaveEvent) ProtoMessage() {}

func (x *UserLeaveEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_apiv1_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLeaveEvent.ProtoReflect.Descriptor instead.
func (*UserLeaveEvent) Descriptor() ([]byte, []int) {
	return file_api_v1_apiv1_proto_rawDescGZIP(), []int{20}
}

func (x *UserLeaveEvent) GetUser() *EventUser {
	if x != nil {
		return x.User
	}
	return nil
}

// User update's its details
type UserUpdateEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *EventUser             `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	Before        *UserDetails           `protobuf:"bytes,2,opt,name=before" json:"before,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUpdateEvent) Reset() {
	*x = UserUpdateEvent{}
	mi := &file_api_v1_apiv1_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUpdateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUpdateEvent) ProtoMessage() {}

func (x *UserUpdateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_apiv1_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUpdateEvent.ProtoReflect.Descriptor instead.
func (*UserUpdateEvent) Descriptor() ([]byte, []int) {
	return file_api_v1_apiv1_proto_rawDescGZIP(), []int{21}
}

func (x *UserUpdateEvent) GetUser() *EventUser {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UserUpdateEvent) GetBefore() *UserDetails {
	if x != nil {
		return x.Before
	}
	return nil
}

// User status is changed
type UserStatusEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *EventUser             `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	Status        UserStatus             `protobuf:"varint,2,opt,name=status,enum=api.v1.UserStatus" json:"status,omitempty"`
	Before        UserStatus             `protobuf:"varint,3,opt,name=before,enum=api.v1.UserStatus" json:"before,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserStatusEvent) Reset() {
	*x = UserStatusEvent{}
	mi := &file_api_v1_apiv1_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStatusEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStatusEvent) ProtoMessage() {}

func (x *UserStatusEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_apiv1_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStatusEvent.ProtoReflect.Descriptor instead.
func (*UserStatusEvent) Descriptor() ([]byte, []int) {
	return file_api_v1_apiv1_proto_rawDescGZIP(), []int{22}
}

func (x *UserStatusEvent) GetUser() *EventUser {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UserStatusEvent) GetStatus() UserStatus {
	if x != nil {
		return x.Status
	}
	return UserStatus_Default
}

func (x *UserStatusEvent) GetBefore() UserStatus {
	if x != nil {
		return x.Before
	}
	return UserStatus_Default
}

// User is typing a message
type UserTypingEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	User  *EventUser             `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	// receiver user's UUID, or global chatroom on empty
	ReceiverId    *UUID `protobuf:"bytes,2,opt,name=receiver_id,json=receiverId" json:"receiver_id,omitempty"`
	Typing        bool  `protobuf:"varint,3,opt,name=typing" json:"typing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserTypingEvent) Reset() {
	*x = UserTypingEvent{}
	mi := &file_api_v1_apiv1_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserTypingEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTypingEvent) ProtoMessage() {}

func (x *UserTypingEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_apiv1_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTypingEvent.ProtoReflect.Descriptor instead.
func (*UserTypingEvent) Descriptor() ([]byte, []int) {
	return file_api_v1_apiv1_proto_rawDescGZIP(), []int{23}
}

func (x *UserTypingEvent) GetUser() *EventUser {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UserTypingEvent) GetReceiverId() *UUID {
	if x != nil {
		return x.ReceiverId
	}
	return nil
}

func (x *UserTypingEvent) GetTyping() bool {
	if x != nil {
		return x.Typing
	}
	return false
}

// User sends chat message
type ChatSentEvent struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	ChatId *UUID                  `protobuf:"bytes,1,opt,name=chat_id,json=chatId" json:"chat_id,omitempty"` // id of this chat
	User   *EventUser             `protobuf:"bytes,2,opt,name=user" json:"user,omitempty"`
	// receiver user's UUID, or global chatroom on empty
	ReceiverId    *UUID                       `protobuf:"bytes,3,opt,name=receiver_id,json=receiverId" json:"receiver_id,omitempty"`
	ReplyChatId   *UUID                       `protobuf:"bytes,4,opt,name=reply_chat_id,json=replyChatId" json:"reply_chat_id,omitempty"`
	Text          string                      `protobuf:"bytes,5,opt,name=text" json:"text,omitempty"`
	TextEdit      *ChatSentEvent_Edit         `protobuf:"bytes,6,opt,name=text_edit,json=textEdit" json:"text_edit,omitempty"`
	Mentions      []*UserMention              `protobuf:"bytes,7,rep,name=mentions" json:"mentions,omitempty"`
	Emojis        []*ChatSentEvent_EmojiReply `protobuf:"bytes,8,rep,name=emojis" json:"emojis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatSentEvent) Reset() {
	*x = ChatSentEvent{}
	mi := &file_api_v1_apiv1_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatSentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatSentEvent) ProtoMessage() {}

func (x *ChatSentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_apiv1_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatSentEvent.ProtoReflect.Descriptor instead.
func (*ChatSentEvent) Descriptor() ([]byte, []int) {
	return file_api_v1_apiv1_proto_rawDescGZIP(), []int{24}
}

func (x *ChatSentEvent) GetChatId() *UUID {
	if x != nil {
		return x.ChatId
	}
	return nil
}

func (x *ChatSentEvent) GetUser() *EventUser {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *ChatSentEvent) GetReceiverId() *UUID {
	if x != nil {
		return x.ReceiverId
	}
	return nil
}

func (x *ChatSentEvent) GetReplyChatId() *UUID {
	if x != nil {
		return x.ReplyChatId
	}
	return nil
}

func (x *ChatSentEvent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ChatSentEvent) GetTextEdit() *ChatSentEvent_Edit {
	if x != nil {
		return x.TextEdit
	}
	return nil
}

func (x *ChatSentEvent) GetMentions() []*UserMention {
	if x != nil {
		return x.Mentions
	}
	return nil
}

func (x *ChatSentEvent) GetEmojis() []*ChatSentEvent_EmojiReply {
	if x != nil {
		return x.Emojis
	}
	return nil
}

type ChatEditEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        *UUID                  `protobuf:"bytes,1,opt,name=chat_id,json=chatId" json:"chat_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatEditEvent) Reset() {
	*x = ChatEditEvent{}
	mi := &file_api_v1_apiv1_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatEditEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatEditEvent) ProtoMessage() {}

func (x *ChatEditEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_apiv1_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatEditEvent.ProtoReflect.Descriptor instead.
func (*ChatEditEvent) Descriptor() ([]byte, []int) {
	return file_api_v1_apiv1_proto_rawDescGZIP(), []int{25}
}

func (x *ChatEditEvent) GetChatId() *UUID {
	if x != nil {
		return x.ChatId
	}
	return nil
}

func (x *ChatEditEvent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type EmojiReplyEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        *UUID                  `protobuf:"bytes,1,opt,name=chat_id,json=chatId" json:"chat_id,omitempty"`
	Emoji         []byte                 `protobuf:"bytes,2,opt,name=emoji" json:"emoji,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmojiReplyEvent) Reset() {
	*x = EmojiReplyEvent{}
	mi := &file_api_v1_apiv1_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmojiReplyEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmojiReplyEvent) ProtoMessage() {}

func (x *EmojiReplyEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_apiv1_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmojiReplyEvent.ProtoReflect.Descriptor instead.
func (*EmojiReplyEvent) Descriptor() ([]byte, []int) {
	return file_api_v1_apiv1_proto_rawDescGZIP(), []int{26}
}

func (x *EmojiReplyEvent) GetChatId() *UUID {
	if x != nil {
		return x.ChatId
	}
	return nil
}

func (x *EmojiReplyEvent) GetEmoji() []byte {
	if x != nil {
		return x.Emoji
	}
	return nil
}

type EmojiRemoveEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        *UUID                  `protobuf:"bytes,1,opt,name=chat_id,json=chatId" json:"chat_id,omitempty"`
	Emoji         []byte                 `protobuf:"bytes,2,opt,name=emoji" json:"emoji,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmojiRemoveEvent) Reset() {
	*x = EmojiRemoveEvent{}
	mi := &file_api_v1_apiv1_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmojiRemoveEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmojiRemoveEvent) ProtoMessage() {}

func (x *EmojiRemoveEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_apiv1_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmojiRemoveEvent.ProtoReflect.Descriptor instead.
func (*EmojiRemoveEvent) Descriptor() ([]byte, []int) {
	return file_api_v1_apiv1_proto_rawDescGZIP(), []int{27}
}

func (x *EmojiRemoveEvent) GetChatId() *UUID {
	if x != nil {
		return x.ChatId
	}
	return nil
}

func (x *EmojiRemoveEvent) GetEmoji() []byte {
	if x != nil {
		return x.Emoji
	}
	return nil
}

type ActiveUsersResponse_User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *UUID                  `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Details       *UserDetails           `protobuf:"bytes,2,opt,name=details" json:"details,omitempty"`
	Flags         UserFlag               `protobuf:"varint,3,opt,name=flags,enum=api.v1.UserFlag" json:"flags,omitempty"`
	Status        UserStatus             `protobuf:"varint,4,opt,name=status,enum=api.v1.UserStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActiveUsersResponse_User) Reset() {
	*x = ActiveUsersResponse_User{}
	mi := &file_api_v1_apiv1_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveUsersResponse_User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveUsersResponse_User) ProtoMessage() {}

func (x *ActiveUsersResponse_User) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_apiv1_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveUsersResponse_User.ProtoReflect.Descriptor instead.
func (*ActiveUsersResponse_User) Descriptor() ([]byte, []int) {
	return file_api_v1_apiv1_proto_rawDescGZIP(), []int{7, 0}
}

func (x *ActiveUsersResponse_User) GetId() *UUID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *ActiveUsersResponse_User) GetDetails() *UserDetails {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *ActiveUsersResponse_User) GetFlags() UserFlag {
	if x != nil {
		return x.Flags
	}
	return UserFlag_None
}

func (x *ActiveUsersResponse_User) GetStatus() UserStatus {
	if x != nil {
		return x.Status
	}
	return UserStatus_Default
}

type PreviousEventsResponse_PreviousEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Time  *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time" json:"time,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*PreviousEventsResponse_PreviousEvent_UserJoin
	//	*PreviousEventsResponse_PreviousEvent_UserLeave
	//	*PreviousEventsResponse_PreviousEvent_UserUpdate
	//	*PreviousEventsResponse_PreviousEvent_ChatSent
	Event         isPreviousEventsResponse_PreviousEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviousEventsResponse_PreviousEvent) Reset() {
	*x = PreviousEventsResponse_PreviousEvent{}
	mi := &file_api_v1_apiv1_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviousEventsResponse_PreviousEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviousEventsResponse_PreviousEvent) ProtoMessage() {}

func (x *PreviousEventsResponse_PreviousEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_apiv1_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviousEventsResponse_PreviousEvent.ProtoReflect.Descriptor instead.
func (*PreviousEventsResponse_PreviousEvent) Descriptor() ([]byte, []int) {
	return file_api_v1_apiv1_proto_rawDescGZIP(), []int{16, 0}
}

func (x *PreviousEventsResponse_PreviousEvent) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *PreviousEventsResponse_PreviousEvent) GetEvent() isPreviousEventsResponse_PreviousEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *PreviousEventsResponse_PreviousEvent) GetUserJoin() *UserJoinEvent {
	if x != nil {
		if x, ok := x.Event.(*PreviousEventsResponse_PreviousEvent_UserJoin); ok {
			return x.UserJoin
		}
	}
	return nil
}

func (x *PreviousEventsResponse_PreviousEvent) GetUserLeave() *UserLeaveEvent {
	if x != nil {
		if x, ok := x.Event.(*PreviousEventsResponse_PreviousEvent_UserLeave); ok {
			return x.UserLeave
		}
	}
	return nil
}

func (x *PreviousEventsResponse_PreviousEvent) GetUserUpdate() *UserUpdateEvent {
	if x != nil {
		if x, ok := x.Event.(*PreviousEventsResponse_PreviousEvent_UserUpdate); ok {
			return x.UserUpdate
		}
	}
	return nil
}

func (x *PreviousEventsResponse_PreviousEvent) GetChatSent() *ChatSentEvent {
	if x != nil {
		if x, ok := x.Event.(*PreviousEventsResponse_PreviousEvent_ChatSent); ok {
			return x.ChatSent
		}
	}
	return nil
}

type isPreviousEventsResponse_PreviousEvent_Event interface {
	isPreviousEventsResponse_PreviousEvent_Event()
}

type PreviousEventsResponse_PreviousEvent_UserJoin struct {
	UserJoin *UserJoinEvent `protobuf:"bytes,10,opt,name=user_join,json=userJoin,oneof"`
}

type PreviousEventsResponse_PreviousEvent_UserLeave struct {
	UserLeave *UserLeaveEvent `protobuf:"bytes,11,opt,name=user_leave,json=userLeave,oneof"`
}

type PreviousEventsResponse_PreviousEvent_UserUpdate struct {
	UserUpdate *UserUpdateEvent `protobuf:"bytes,12,opt,name=user_update,json=userUpdate,oneof"`
}

type PreviousEventsResponse_PreviousEvent_ChatSent struct {
	ChatSent *ChatSentEvent `protobuf:"bytes,20,opt,name=chat_sent,json=chatSent,oneof"`
}

func (*PreviousEventsResponse_PreviousEvent_UserJoin) isPreviousEventsResponse_PreviousEvent_Event() {
}

func (*PreviousEventsResponse_PreviousEvent_UserLeave) isPreviousEventsResponse_PreviousEvent_Event() {
}

func (*PreviousEventsResponse_PreviousEvent_UserUpdate) isPreviousEventsResponse_PreviousEvent_Event() {
}

func (*PreviousEventsResponse_PreviousEvent_ChatSent) isPreviousEventsResponse_PreviousEvent_Event() {
}

type ChatSentEvent_Edit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time" json:"time,omitempty"`
	Original      string                 `protobuf:"bytes,2,opt,name=original" json:"original,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatSentEvent_Edit) Reset() {
	*x = ChatSentEvent_Edit{}
	mi := &file_api_v1_apiv1_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatSentEvent_Edit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatSentEvent_Edit) ProtoMessage() {}

func (x *ChatSentEvent_Edit) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_apiv1_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatSentEvent_Edit.ProtoReflect.Descriptor instead.
func (*ChatSentEvent_Edit) Descriptor() ([]byte, []int) {
	return file_api_v1_apiv1_proto_rawDescGZIP(), []int{24, 0}
}

func (x *ChatSentEvent_Edit) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *ChatSentEvent_Edit) GetOriginal() string {
	if x != nil {
		return x.Original
	}
	return ""
}

type ChatSentEvent_EmojiReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time" json:"time,omitempty"`
	User          *EventUser             `protobuf:"bytes,2,opt,name=user" json:"user,omitempty"`
	Emoji         []byte                 `protobuf:"bytes,3,opt,name=emoji" json:"emoji,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatSentEvent_EmojiReply) Reset() {
	*x = ChatSentEvent_EmojiReply{}
	mi := &file_api_v1_apiv1_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatSentEvent_EmojiReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatSentEvent_EmojiReply) ProtoMessage() {}

func (x *ChatSentEvent_EmojiReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_apiv1_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatSentEvent_EmojiReply.ProtoReflect.Descriptor instead.
func (*ChatSentEvent_EmojiReply) Descriptor() ([]byte, []int) {
	return file_api_v1_apiv1_proto_rawDescGZIP(), []int{24, 1}
}

func (x *ChatSentEvent_EmojiReply) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *ChatSentEvent_EmojiReply) GetUser() *EventUser {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *ChatSentEvent_EmojiReply) GetEmoji() []byte {
	if x != nil {
		return x.Emoji
	}
	return nil
}

var File_api_v1_apiv1_proto protoreflect.FileDescriptor

const file_api_v1_apiv1_proto_rawDesc = "" +
	"\n" +
	"\x12api/v1/apiv1.proto\x12\x06api.v1\x1a\x19google/protobuf/any.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x1c\n" +
	"\x04UUID\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\x1d\n" +
	"\x05Color\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\x8b\x01\n" +
	"\vUserDetails\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\binitials\x18\x02 \x01(\tR\binitials\x12%\n" +
	"\x06color1\x18\x03 \x01(\v2\r.api.v1.ColorR\x06color1\x12%\n" +
	"\x06color2\x18\x04 \x01(\v2\r.api.v1.ColorR\x06color2\"Q\n" +
	"\vUserMention\x12%\n" +
	"\auser_id\x18\x01 \x01(\v2\f.api.v1.UUIDR\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\"^\n" +
	"\vJoinRequest\x12'\n" +
	"\x04user\x18\x01 \x01(\v2\x13.api.v1.UserDetailsR\x04user\x12&\n" +
	"\x05flags\x18\x02 \x01(\x0e2\x10.api.v1.UserFlagR\x05flags\"$\n" +
	"\fJoinResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"%\n" +
	"\rRenewResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\xa7\x02\n" +
	"\x13ActiveUsersResponse\x12.\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x126\n" +
	"\x05users\x18\x02 \x03(\v2 .api.v1.ActiveUsersResponse.UserR\x05users\x1a\xa7\x01\n" +
	"\x04User\x12\x1c\n" +
	"\x02id\x18\x01 \x01(\v2\f.api.v1.UUIDR\x02id\x12-\n" +
	"\adetails\x18\x02 \x01(\v2\x13.api.v1.UserDetailsR\adetails\x12&\n" +
	"\x05flags\x18\x03 \x01(\x0e2\x10.api.v1.UserFlagR\x05flags\x12*\n" +
	"\x06status\x18\x04 \x01(\x0e2\x12.api.v1.UserStatusR\x06status\"E\n" +
	"\x14UpdateDetailsRequest\x12-\n" +
	"\adetails\x18\x01 \x01(\v2\x13.api.v1.UserDetailsR\adetails\"A\n" +
	"\x13UpdateStatusRequest\x12*\n" +
	"\x06status\x18\x01 \x01(\x0e2\x12.api.v1.UserStatusR\x06status\"^\n" +
	"\x15IndicateTypingRequest\x12-\n" +
	"\vreceiver_id\x18\x01 \x01(\v2\f.api.v1.UUIDR\n" +
	"receiverId\x12\x16\n" +
	"\x06typing\x18\x02 \x01(\bR\x06typing\"\xe7\x01\n" +
	"\x0fSendChatRequest\x12.\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12-\n" +
	"\vreceiver_id\x18\x02 \x01(\v2\f.api.v1.UUIDR\n" +
	"receiverId\x120\n" +
	"\rreply_chat_id\x18\x03 \x01(\v2\f.api.v1.UUIDR\vreplyChatId\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12/\n" +
	"\bmentions\x18\x05 \x03(\v2\x13.api.v1.UserMentionR\bmentions\"|\n" +
	"\x0fEditChatRequest\x12.\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12%\n" +
	"\achat_id\x18\x02 \x01(\v2\f.api.v1.UUIDR\x06chatId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\"\x8b\x01\n" +
	"\x11EmojiReplyRequest\x12.\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x120\n" +
	"\rreply_chat_id\x18\x03 \x01(\v2\f.api.v1.UUIDR\vreplyChatId\x12\x14\n" +
	"\x05emoji\x18\x04 \x01(\fR\x05emoji\"X\n" +
	"\tEventUser\x12\x1c\n" +
	"\x02id\x18\x01 \x01(\v2\f.api.v1.UUIDR\x02id\x12-\n" +
	"\adetails\x18\x02 \x01(\v2\x13.api.v1.UserDetailsR\adetails\"h\n" +
	"\x15PreviousEventsRequest\x129\n" +
	"\n" +
	"until_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tuntilTime\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x04R\x05limit\"\x8c\x03\n" +
	"\x16PreviousEventsResponse\x12F\n" +
	"\ahistory\x18\x01 \x03(\v2,.api.v1.PreviousEventsResponse.PreviousEventR\ahistory\x1a\xa9\x02\n" +
	"\rPreviousEvent\x12.\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x124\n" +
	"\tuser_join\x18\n" +
	" \x01(\v2\x15.api.v1.UserJoinEventH\x00R\buserJoin\x127\n" +
	"\n" +
	"user_leave\x18\v \x01(\v2\x16.api.v1.UserLeaveEventH\x00R\tuserLeave\x12:\n" +
	"\vuser_update\x18\f \x01(\v2\x17.api.v1.UserUpdateEventH\x00R\n" +
	"userUpdate\x124\n" +
	"\tchat_sent\x18\x14 \x01(\v2\x15.api.v1.ChatSentEventH\x00R\bchatSentB\a\n" +
	"\x05event\"J\n" +
	"\x12EventStreamRequest\x12\x16\n" +
	"\x05start\x18\x01 \x01(\tH\x00R\x05start\x12\x12\n" +
	"\x03ack\x18\x02 \x01(\tH\x00R\x03ackB\b\n" +
	"\x06stream\"\xd8\x04\n" +
	"\x13EventStreamResponse\x12.\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x124\n" +
	"\tuser_join\x18\n" +
	" \x01(\v2\x15.api.v1.UserJoinEventH\x00R\buserJoin\x127\n" +
	"\n" +
	"user_leave\x18\v \x01(\v2\x16.api.v1.UserLeaveEventH\x00R\tuserLeave\x12:\n" +
	"\vuser_update\x18\f \x01(\v2\x17.api.v1.UserUpdateEventH\x00R\n" +
	"userUpdate\x12:\n" +
	"\vuser_status\x18\r \x01(\v2\x17.api.v1.UserStatusEventH\x00R\n" +
	"userStatus\x12:\n" +
	"\vuser_typing\x18\x0e \x01(\v2\x17.api.v1.UserTypingEventH\x00R\n" +
	"userTyping\x124\n" +
	"\tchat_sent\x18\x14 \x01(\v2\x15.api.v1.ChatSentEventH\x00R\bchatSent\x124\n" +
	"\tchat_edit\x18\x15 \x01(\v2\x15.api.v1.ChatEditEventH\x00R\bchatEdit\x12:\n" +
	"\vemoji_reply\x18\x16 \x01(\v2\x17.api.v1.EmojiReplyEventH\x00R\n" +
	"emojiReply\x12=\n" +
	"\femoji_remove\x18\x17 \x01(\v2\x18.api.v1.EmojiRemoveEventH\x00R\vemojiRemoveB\a\n" +
	"\x05event\"^\n" +
	"\rUserJoinEvent\x12%\n" +
	"\x04user\x18\x01 \x01(\v2\x11.api.v1.EventUserR\x04user\x12&\n" +
	"\x05flags\x18\x02 \x01(\x0e2\x10.api.v1.UserFlagR\x05flags\"7\n" +
	"\x0eUserLeaveEvent\x12%\n" +
	"\x04user\x18\x01 \x01(\v2\x11.api.v1.EventUserR\x04user\"e\n" +
	"\x0fUserUpdateEvent\x12%\n" +
	"\x04user\x18\x01 \x01(\v2\x11.api.v1.EventUserR\x04user\x12+\n" +
	"\x06before\x18\x02 \x01(\v2\x13.api.v1.UserDetailsR\x06before\"\x90\x01\n" +
	"\x0fUserStatusEvent\x12%\n" +
	"\x04user\x18\x01 \x01(\v2\x11.api.v1.EventUserR\x04user\x12*\n" +
	"\x06status\x18\x02 \x01(\x0e2\x12.api.v1.UserStatusR\x06status\x12*\n" +
	"\x06before\x18\x03 \x01(\x0e2\x12.api.v1.UserStatusR\x06before\"\x7f\n" +
	"\x0fUserTypingEvent\x12%\n" +
	"\x04user\x18\x01 \x01(\v2\x11.api.v1.EventUserR\x04user\x12-\n" +
	"\vreceiver_id\x18\x02 \x01(\v2\f.api.v1.UUIDR\n" +
	"receiverId\x12\x16\n" +
	"\x06typing\x18\x03 \x01(\bR\x06typing\"\xc5\x04\n" +
	"\rChatSentEvent\x12%\n" +
	"\achat_id\x18\x01 \x01(\v2\f.api.v1.UUIDR\x06chatId\x12%\n" +
	"\x04user\x18\x02 \x01(\v2\x11.api.v1.EventUserR\x04user\x12-\n" +
	"\vreceiver_id\x18\x03 \x01(\v2\f.api.v1.UUIDR\n" +
	"receiverId\x120\n" +
	"\rreply_chat_id\x18\x04 \x01(\v2\f.api.v1.UUIDR\vreplyChatId\x12\x12\n" +
	"\x04text\x18\x05 \x01(\tR\x04text\x127\n" +
	"\ttext_edit\x18\x06 \x01(\v2\x1a.api.v1.ChatSentEvent.EditR\btextEdit\x12/\n" +
	"\bmentions\x18\a \x03(\v2\x13.api.v1.UserMentionR\bmentions\x128\n" +
	"\x06emojis\x18\b \x03(\v2 .api.v1.ChatSentEvent.EmojiReplyR\x06emojis\x1aR\n" +
	"\x04Edit\x12.\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x1a\n" +
	"\boriginal\x18\x02 \x01(\tR\boriginal\x1ay\n" +
	"\n" +
	"EmojiReply\x12.\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12%\n" +
	"\x04user\x18\x02 \x01(\v2\x11.api.v1.EventUserR\x04user\x12\x14\n" +
	"\x05emoji\x18\x03 \x01(\fR\x05emoji\"J\n" +
	"\rChatEditEvent\x12%\n" +
	"\achat_id\x18\x01 \x01(\v2\f.api.v1.UUIDR\x06chatId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"N\n" +
	"\x0fEmojiReplyEvent\x12%\n" +
	"\achat_id\x18\x01 \x01(\v2\f.api.v1.UUIDR\x06chatId\x12\x14\n" +
	"\x05emoji\x18\x02 \x01(\fR\x05emoji\"O\n" +
	"\x10EmojiRemoveEvent\x12%\n" +
	"\achat_id\x18\x01 \x01(\v2\f.api.v1.UUIDR\x06chatId\x12\x14\n" +
	"\x05emoji\x18\x02 \x01(\fR\x05emoji*-\n" +
	"\n" +
	"UserStatus\x12\v\n" +
	"\aDefault\x10\x00\x12\b\n" +
	"\x04Busy\x10\x01\x12\b\n" +
	"\x04Away\x10\x02*\x1f\n" +
	"\bUserFlag\x12\b\n" +
	"\x04None\x10\x00\x12\t\n" +
	"\x05IsBot\x10\x012\xb7\x01\n" +
	"\vAuthService\x123\n" +
	"\x04Join\x12\x13.api.v1.JoinRequest\x1a\x14.api.v1.JoinResponse\"\x00\x128\n" +
	"\x05Renew\x12\x16.google.protobuf.Empty\x1a\x15.api.v1.RenewResponse\"\x00\x129\n" +
	"\x05Leave\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x002\xed\x03\n" +
	"\vUserService\x12D\n" +
	"\vActiveUsers\x12\x16.google.protobuf.Empty\x1a\x1b.api.v1.ActiveUsersResponse\"\x00\x12G\n" +
	"\rUpdateDetails\x12\x1c.api.v1.UpdateDetailsRequest\x1a\x16.google.protobuf.Empty\"\x00\x12E\n" +
	"\fUpdateStatus\x12\x1b.api.v1.UpdateStatusRequest\x1a\x16.google.protobuf.Empty\"\x00\x12I\n" +
	"\x0eIndicateTyping\x12\x1d.api.v1.IndicateTypingRequest\x1a\x16.google.protobuf.Empty\"\x00\x12=\n" +
	"\bSendChat\x12\x17.api.v1.SendChatRequest\x1a\x16.google.protobuf.Empty\"\x00\x12;\n" +
	"\bEditChat\x12\x15.api.v1.ChatEditEvent\x1a\x16.google.protobuf.Empty\"\x00\x12A\n" +
	"\n" +
	"EmojiReply\x12\x19.api.v1.EmojiReplyRequest\x1a\x16.google.protobuf.Empty\"\x002\xaa\x01\n" +
	"\rEventsService\x12Q\n" +
	"\x0ePreviousEvents\x12\x1d.api.v1.PreviousEventsRequest\x1a\x1e.api.v1.PreviousEventsResponse\"\x00\x12F\n" +
	"\vEventStream\x12\x16.google.protobuf.Empty\x1a\x1b.api.v1.EventStreamResponse\"\x000\x01B4Z-github.com/roeldev/demo-chatroom/api/v1;apiv1\x92\x03\x02\b\x02b\beditionsp\xe8\a"

var (
	file_api_v1_apiv1_proto_rawDescOnce sync.Once
	file_api_v1_apiv1_proto_rawDescData []byte
)

func file_api_v1_apiv1_proto_rawDescGZIP() []byte {
	file_api_v1_apiv1_proto_rawDescOnce.Do(func() {
		file_api_v1_apiv1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_apiv1_proto_rawDesc), len(file_api_v1_apiv1_proto_rawDesc)))
	})
	return file_api_v1_apiv1_proto_rawDescData
}

var file_api_v1_apiv1_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_v1_apiv1_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_api_v1_apiv1_proto_goTypes = []any{
	(UserStatus)(0),                              // 0: api.v1.UserStatus
	(UserFlag)(0),                                // 1: api.v1.UserFlag
	(*UUID)(nil),                                 // 2: api.v1.UUID
	(*Color)(nil),                                // 3: api.v1.Color
	(*UserDetails)(nil),                          // 4: api.v1.UserDetails
	(*UserMention)(nil),                          // 5: api.v1.UserMention
	(*JoinRequest)(nil),                          // 6: api.v1.JoinRequest
	(*JoinResponse)(nil),                         // 7: api.v1.JoinResponse
	(*RenewResponse)(nil),                        // 8: api.v1.RenewResponse
	(*ActiveUsersResponse)(nil),                  // 9: api.v1.ActiveUsersResponse
	(*UpdateDetailsRequest)(nil),                 // 10: api.v1.UpdateDetailsRequest
	(*UpdateStatusRequest)(nil),                  // 11: api.v1.UpdateStatusRequest
	(*IndicateTypingRequest)(nil),                // 12: api.v1.IndicateTypingRequest
	(*SendChatRequest)(nil),                      // 13: api.v1.SendChatRequest
	(*EditChatRequest)(nil),                      // 14: api.v1.EditChatRequest
	(*EmojiReplyRequest)(nil),                    // 15: api.v1.EmojiReplyRequest
	(*EventUser)(nil),                            // 16: api.v1.EventUser
	(*PreviousEventsRequest)(nil),                // 17: api.v1.PreviousEventsRequest
	(*PreviousEventsResponse)(nil),               // 18: api.v1.PreviousEventsResponse
	(*EventStreamRequest)(nil),                   // 19: api.v1.EventStreamRequest
	(*EventStreamResponse)(nil),                  // 20: api.v1.EventStreamResponse
	(*UserJoinEvent)(nil),                        // 21: api.v1.UserJoinEvent
	(*UserLeaveEvent)(nil),                       // 22: api.v1.UserLeaveEvent
	(*UserUpdateEvent)(nil),                      // 23: api.v1.UserUpdateEvent
	(*UserStatusEvent)(nil),                      // 24: api.v1.UserStatusEvent
	(*UserTypingEvent)(nil),                      // 25: api.v1.UserTypingEvent
	(*ChatSentEvent)(nil),                        // 26: api.v1.ChatSentEvent
	(*ChatEditEvent)(nil),                        // 27: api.v1.ChatEditEvent
	(*EmojiReplyEvent)(nil),                      // 28: api.v1.EmojiReplyEvent
	(*EmojiRemoveEvent)(nil),                     // 29: api.v1.EmojiRemoveEvent
	(*ActiveUsersResponse_User)(nil),             // 30: api.v1.ActiveUsersResponse.User
	(*PreviousEventsResponse_PreviousEvent)(nil), // 31: api.v1.PreviousEventsResponse.PreviousEvent
	(*ChatSentEvent_Edit)(nil),                   // 32: api.v1.ChatSentEvent.Edit
	(*ChatSentEvent_EmojiReply)(nil),             // 33: api.v1.ChatSentEvent.EmojiReply
	(*timestamppb.Timestamp)(nil),                // 34: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                        // 35: google.protobuf.Empty
}
var file_api_v1_apiv1_proto_depIdxs = []int32{
	3,  // 0: api.v1.UserDetails.color1:type_name -> api.v1.Color
	3,  // 1: api.v1.UserDetails.color2:type_name -> api.v1.Color
	2,  // 2: api.v1.UserMention.user_id:type_name -> api.v1.UUID
	4,  // 3: api.v1.JoinRequest.user:type_name -> api.v1.UserDetails
	1,  // 4: api.v1.JoinRequest.flags:type_name -> api.v1.UserFlag
	34, // 5: api.v1.ActiveUsersResponse.time:type_name -> google.protobuf.Timestamp
	30, // 6: api.v1.ActiveUsersResponse.users:type_name -> api.v1.ActiveUsersResponse.User
	4,  // 7: api.v1.UpdateDetailsRequest.details:type_name -> api.v1.UserDetails
	0,  // 8: api.v1.UpdateStatusRequest.status:type_name -> api.v1.UserStatus
	2,  // 9: api.v1.IndicateTypingRequest.receiver_id:type_name -> api.v1.UUID
	34, // 10: api.v1.SendChatRequest.time:type_name -> google.protobuf.Timestamp
	2,  // 11: api.v1.SendChatRequest.receiver_id:type_name -> api.v1.UUID
	2,  // 12: api.v1.SendChatRequest.reply_chat_id:type_name -> api.v1.UUID
	5,  // 13: api.v1.SendChatRequest.mentions:type_name -> api.v1.UserMention
	34, // 14: api.v1.EditChatRequest.time:type_name -> google.protobuf.Timestamp
	2,  // 15: api.v1.EditChatRequest.chat_id:type_name -> api.v1.UUID
	34, // 16: api.v1.EmojiReplyRequest.time:type_name -> google.protobuf.Timestamp
	2,  // 17: api.v1.EmojiReplyRequest.reply_chat_id:type_name -> api.v1.UUID
	2,  // 18: api.v1.EventUser.id:type_name -> api.v1.UUID
	4,  // 19: api.v1.EventUser.details:type_name -> api.v1.UserDetails
	34, // 20: api.v1.PreviousEventsRequest.until_time:type_name -> google.protobuf.Timestamp
	31, // 21: api.v1.PreviousEventsResponse.history:type_name -> api.v1.PreviousEventsResponse.PreviousEvent
	34, // 22: api.v1.EventStreamResponse.time:type_name -> google.protobuf.Timestamp
	21, // 23: api.v1.EventStreamResponse.user_join:type_name -> api.v1.UserJoinEvent
	22, // 24: api.v1.EventStreamResponse.user_leave:type_name -> api.v1.UserLeaveEvent
	23, // 25: api.v1.EventStreamResponse.user_update:type_name -> api.v1.UserUpdateEvent
	24, // 26: api.v1.EventStreamResponse.user_status:type_name -> api.v1.UserStatusEvent
	25, // 27: api.v1.EventStreamResponse.user_typing:type_name -> api.v1.UserTypingEvent
	26, // 28: api.v1.EventStreamResponse.chat_sent:type_name -> api.v1.ChatSentEvent
	27, // 29: api.v1.EventStreamResponse.chat_edit:type_name -> api.v1.ChatEditEvent
	28, // 30: api.v1.EventStreamResponse.emoji_reply:type_name -> api.v1.EmojiReplyEvent
	29, // 31: api.v1.EventStreamResponse.emoji_remove:type_name -> api.v1.EmojiRemoveEvent
	16, // 32: api.v1.UserJoinEvent.user:type_name -> api.v1.EventUser
	1,  // 33: api.v1.UserJoinEvent.flags:type_name -> api.v1.UserFlag
	16, // 34: api.v1.UserLeaveEvent.user:type_name -> api.v1.EventUser
	16, // 35: api.v1.UserUpdateEvent.user:type_name -> api.v1.EventUser
	4,  // 36: api.v1.UserUpdateEvent.before:type_name -> api.v1.UserDetails
	16, // 37: api.v1.UserStatusEvent.user:type_name -> api.v1.EventUser
	0,  // 38: api.v1.UserStatusEvent.status:type_name -> api.v1.UserStatus
	0,  // 39: api.v1.UserStatusEvent.before:type_name -> api.v1.UserStatus
	16, // 40: api.v1.UserTypingEvent.user:type_name -> api.v1.EventUser
	2,  // 41: api.v1.UserTypingEvent.receiver_id:type_name -> api.v1.UUID
	2,  // 42: api.v1.ChatSentEvent.chat_id:type_name -> api.v1.UUID
	16, // 43: api.v1.ChatSentEvent.user:type_name -> api.v1.EventUser
	2,  // 44: api.v1.ChatSentEvent.receiver_id:type_name -> api.v1.UUID
	2,  // 45: api.v1.ChatSentEvent.reply_chat_id:type_name -> api.v1.UUID
	32, // 46: api.v1.ChatSentEvent.text_edit:type_name -> api.v1.ChatSentEvent.Edit
	5,  // 47: api.v1.ChatSentEvent.mentions:type_name -> api.v1.UserMention
	33, // 48: api.v1.ChatSentEvent.emojis:type_name -> api.v1.ChatSentEvent.EmojiReply
	2,  // 49: api.v1.ChatEditEvent.chat_id:type_name -> api.v1.UUID
	2,  // 50: api.v1.EmojiReplyEvent.chat_id:type_name -> api.v1.UUID
	2,  // 51: api.v1.EmojiRemoveEvent.chat_id:type_name -> api.v1.UUID
	2,  // 52: api.v1.ActiveUsersResponse.User.id:type_name -> api.v1.UUID
	4,  // 53: api.v1.ActiveUsersResponse.User.details:type_name -> api.v1.UserDetails
	1,  // 54: api.v1.ActiveUsersResponse.User.flags:type_name -> api.v1.UserFlag
	0,  // 55: api.v1.ActiveUsersResponse.User.status:type_name -> api.v1.UserStatus
	34, // 56: api.v1.PreviousEventsResponse.PreviousEvent.time:type_name -> google.protobuf.Timestamp
	21, // 57: api.v1.PreviousEventsResponse.PreviousEvent.user_join:type_name -> api.v1.UserJoinEvent
	22, // 58: api.v1.PreviousEventsResponse.PreviousEvent.user_leave:type_name -> api.v1.UserLeaveEvent
	23, // 59: api.v1.PreviousEventsResponse.PreviousEvent.user_update:type_name -> api.v1.UserUpdateEvent
	26, // 60: api.v1.PreviousEventsResponse.PreviousEvent.chat_sent:type_name -> api.v1.ChatSentEvent
	34, // 61: api.v1.ChatSentEvent.Edit.time:type_name -> google.protobuf.Timestamp
	34, // 62: api.v1.ChatSentEvent.EmojiReply.time:type_name -> google.protobuf.Timestamp
	16, // 63: api.v1.ChatSentEvent.EmojiReply.user:type_name -> api.v1.EventUser
	6,  // 64: api.v1.AuthService.Join:input_type -> api.v1.JoinRequest
	35, // 65: api.v1.AuthService.Renew:input_type -> google.protobuf.Empty
	35, // 66: api.v1.AuthService.Leave:input_type -> google.protobuf.Empty
	35, // 67: api.v1.UserService.ActiveUsers:input_type -> google.protobuf.Empty
	10, // 68: api.v1.UserService.UpdateDetails:input_type -> api.v1.UpdateDetailsRequest
	11, // 69: api.v1.UserService.UpdateStatus:input_type -> api.v1.UpdateStatusRequest
	12, // 70: api.v1.UserService.IndicateTyping:input_type -> api.v1.IndicateTypingRequest
	13, // 71: api.v1.UserService.SendChat:input_type -> api.v1.SendChatRequest
	27, // 72: api.v1.UserService.EditChat:input_type -> api.v1.ChatEditEvent
	15, // 73: api.v1.UserService.EmojiReply:input_type -> api.v1.EmojiReplyRequest
	17, // 74: api.v1.EventsService.PreviousEvents:input_type -> api.v1.PreviousEventsRequest
	35, // 75: api.v1.EventsService.EventStream:input_type -> google.protobuf.Empty
	7,  // 76: api.v1.AuthService.Join:output_type -> api.v1.JoinResponse
	8,  // 77: api.v1.AuthService.Renew:output_type -> api.v1.RenewResponse
	35, // 78: api.v1.AuthService.Leave:output_type -> google.protobuf.Empty
	9,  // 79: api.v1.UserService.ActiveUsers:output_type -> api.v1.ActiveUsersResponse
	35, // 80: api.v1.UserService.UpdateDetails:output_type -> google.protobuf.Empty
	35, // 81: api.v1.UserService.UpdateStatus:output_type -> google.protobuf.Empty
	35, // 82: api.v1.UserService.IndicateTyping:output_type -> google.protobuf.Empty
	35, // 83: api.v1.UserService.SendChat:output_type -> google.protobuf.Empty
	35, // 84: api.v1.UserService.EditChat:output_type -> google.protobuf.Empty
	35, // 85: api.v1.UserService.EmojiReply:output_type -> google.protobuf.Empty
	18, // 86: api.v1.EventsService.PreviousEvents:output_type -> api.v1.PreviousEventsResponse
	20, // 87: api.v1.EventsService.EventStream:output_type -> api.v1.EventStreamResponse
	76, // [76:88] is the sub-list for method output_type
	64, // [64:76] is the sub-list for method input_type
	64, // [64:64] is the sub-list for extension type_name
	64, // [64:64] is the sub-list for extension extendee
	0,  // [0:64] is the sub-list for field type_name
}

func init() { file_api_v1_apiv1_proto_init() }
func file_api_v1_apiv1_proto_init() {
	if File_api_v1_apiv1_proto != nil {
		return
	}
	file_api_v1_apiv1_proto_msgTypes[17].OneofWrappers = []any{
		(*EventStreamRequest_Start)(nil),
		(*EventStreamRequest_Ack)(nil),
	}
	file_api_v1_apiv1_proto_msgTypes[18].OneofWrappers = []any{
		(*EventStreamResponse_UserJoin)(nil),
		(*EventStreamResponse_UserLeave)(nil),
		(*EventStreamResponse_UserUpdate)(nil),
		(*EventStreamResponse_UserStatus)(nil),
		(*EventStreamResponse_UserTyping)(nil),
		(*EventStreamResponse_ChatSent)(nil),
		(*EventStreamResponse_ChatEdit)(nil),
		(*EventStreamResponse_EmojiReply)(nil),
		(*EventStreamResponse_EmojiRemove)(nil),
	}
	file_api_v1_apiv1_proto_msgTypes[29].OneofWrappers = []any{
		(*PreviousEventsResponse_PreviousEvent_UserJoin)(nil),
		(*PreviousEventsResponse_PreviousEvent_UserLeave)(nil),
		(*PreviousEventsResponse_PreviousEvent_UserUpdate)(nil),
		(*PreviousEventsResponse_PreviousEvent_ChatSent)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_apiv1_proto_rawDesc), len(file_api_v1_apiv1_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_api_v1_apiv1_proto_goTypes,
		DependencyIndexes: file_api_v1_apiv1_proto_depIdxs,
		EnumInfos:         file_api_v1_apiv1_proto_enumTypes,
		MessageInfos:      file_api_v1_apiv1_proto_msgTypes,
	}.Build()
	File_api_v1_apiv1_proto = out.File
	file_api_v1_apiv1_proto_goTypes = nil
	file_api_v1_apiv1_proto_depIdxs = nil
}
